### ISSUE TITLE
Rename package?

### ISSUE THREAD

**Issue by gunnarvoet** [gunnarvoet/gadcp#10]
@jessecusack if you are interested in joining and developing this package a bit further, this would be the time to think about whether the name is appropriate. Lacking imagination, I just gave it my initial. I would be happy to change the name if you have a good idea.

**Comment by jessecusack** [comment]
Nothing great comes to mind. Maybe adcpproc to be consistent with some of your other packages?

**Comment by jessecusack** [comment]
@JessCG suggested 'velociraptor'

**Comment by JessCG** [comment]
I was thinking more along the lines of velosearaptor or veloseaty to stick with your 'sea' theme. ;)

**Comment by gunnarvoet** [comment]
Ha, maybe you are on to something! Veloseaty looks weird but also kind of fun!

**Comment by JessCG** [comment]
ADseaP? I can keep going... ;)

**Comment by gunnarvoet** [comment]
I thought of that a couple days ago! Not capitalized though, just adseap...

**Comment by jessecusack** [comment]
velosearaptor is my favourite because it is silly and memorable! I find adseap looks a little odd and it isn't obvious how to pronounce it at first. I think @gunnarvoet should have the final say since he started this package :)

**Comment by gunnarvoet** [comment]
If anyone comes up with a picture of a dinosaur that has acoustic beams coming out if its eyes then I am sold on the Jurassic Park theme =)

**Comment by JessCG** [comment]
Double-vote on @gunnarvoet's request!!! Upward- and downward-flying velosearaptors. Then, I will make T-Shirts to promote the package.

**Comment by jessecusack** [comment]
What about #36 for a first attempt?

**Comment by gunnarvoet** [comment]
I think we are set here - I will open a new issue for actually renaming the package. Thanks for coming up with this theme and make sure to check out the logo that's already live at https://gunnarvoet.github.io/gadcp/gadcp.html
